# Model arguments
model_name_or_path: princeton-nlp/Llama-3-Base-8B-SFT
torch_dtype: null
use_flash_attention_2: true

# Data training arguments
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# SimPOTrainer arguments
bf16: True
beta: 0.01
do_eval: false
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: zephyr-7b-dpo-full
learning_rate: 6.0e-7
log_level: info
logging_steps: 5
ddp_timeout: 10000
loss_type: "DPO"
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
run_name: Llama-7b-base-dpo
output_dir: data/Llama-7b-dpo
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
push_to_hub: False
report_to:
- wandb
save_strategy: "steps"
save_steps: 1000000
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
